name: Python Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Ensure test_data directory exists
      run: mkdir -p test_data

    - name: Test Case 1 
      run: |
        python3 find_lowest_number.py test_data/test1_input.txt output1.txt 
        diff output1.txt test_data/test1_expected.txt

    - name: Test Case 2 
      run: |
        python3 find_lowest_number.py test_data/test2_input.txt output2.txt 
        diff output2.txt test_data/test2_expected.txt

    - name: Test Case 3 
      run: |
        python3 find_lowest_number.py test_data/test3_input.txt output3.txt 
        diff output3.txt test_data/test3_expected.txt

    
